name: API - Docker build and push

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    
    - name: Build and Docker image
      run: |
        # sh scripts/build_container.sh
        cd ./api/
        docker build -t terumo-core-api .
        docker tag terumo-core-api terumoapp/terumo-core-api:latest

    - name: Push Docker image
      run: |
        # sh scripts/push_image.sh
        docker push terumoapp/terumo-core-api:latest