name: Worker - Docker build and push

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    
    - name: Build and Docker image
      run: |
        # sh scripts/build_container.sh
        cd ./celery_index_worker/
        docker build -t terumo-celery-worker .
        docker tag terumo-celery-worker terumoapp/terumo-celery-worker:latest

    - name: Push Docker image
      run: |
        # sh scripts/push_image.sh
        docker push terumoapp/terumo-celery-worker:latest